# Generated by Django 6.0.3 on 2026-04-10 11:01

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gbsapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='billingcase',
            name='vat_includes',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='payroll',
            name='customer_role',
            field=models.CharField(default='Unselected', max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='billingcase',
            name='vat_percent',
            field=models.DecimalField(choices=[(Decimal('0.00'), '0%'), (Decimal('10.00'), '10%'), (Decimal('10.00'), '13.5%'), (Decimal('24.00'), '25.5%')], decimal_places=2, default=Decimal('25.5'), max_digits=4),
        ),
        migrations.AlterField(
            model_name='customer',
            name='custom_role',
            field=models.CharField(choices=[('light entrepreneur', 'Kevytyrittäjä'), ('employee', 'Työntekijä')], max_length=20),
        ),
    ]
