# Generated by Django 6.0.3 on 2026-04-13 07:26

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gbsapp', '0002_billingcase_vat_includes_payroll_customer_role_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billingcase',
            name='vat_percent',
            field=models.DecimalField(choices=[(Decimal('0.00'), '0%'), (Decimal('10.00'), '10%'), (Decimal('13.50'), '13.5%'), (Decimal('25.50'), '25.5%')], decimal_places=2, default=Decimal('25.50'), max_digits=4),
        ),
    ]
