# Generated by Django 6.0.3 on 2026-04-13 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gbsapp', '0003_alter_billingcase_vat_percent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billingcase',
            name='vat_percent',
            field=models.DecimalField(choices=[(25.5, 'ALV 25,5 %'), (13.5, 'ALV 13,5 %'), (10, 'ALV 10 %'), (0, 'ALV 0 %')], decimal_places=2, max_digits=5),
        ),
    ]
