# Generated by Django 6.0.3 on 2026-04-13 08:59

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gbsapp', '0004_alter_billingcase_vat_percent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billingcase',
            name='vat_percent',
            field=models.DecimalField(choices=[(Decimal('25.50'), 'ALV 25,50 %'), (Decimal('13.50'), 'ALV 13,50 %'), (Decimal('10.00'), 'ALV 10,00 %'), (Decimal('0.00'), 'ALV 0,00 %')], decimal_places=2, max_digits=5),
        ),
    ]
