# Generated by Django 6.0.3 on 2026-04-16 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gbsapp', '0005_alter_billingcase_vat_percent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billingcase',
            name='stage',
            field=models.CharField(choices=[('open', 'Open'), ('contract sent', 'Contract Sent'), ('contract accepted', 'Contract Accepted'), ('contract rejected', 'Contract Rejected'), ('assignment', 'Assignment'), ('job done', 'Job Done'), ('invoice sent', 'Invoice Sent'), ('invoice paid', 'Invoice Paid'), ('debt collection', 'Debt Collection'), ('closed', 'Closed'), ('canceled', 'Canceled')], max_length=20),
        ),
    ]
