# Generated by Django 6.0.3 on 2026-04-16 11:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gbsapp', '0006_alter_billingcase_stage'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BilligCustomers',
            new_name='BillingCustomers',
        ),
    ]
