# Generated by Django 6.0.3 on 2026-04-16 11:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gbsapp', '0007_rename_billigcustomers_billingcustomers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billingcase',
            name='billing_cust_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='billingCase_billing_cust_id', to='gbsapp.billingcustomers'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='billing_cust_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contract_billing_cust_id', to='gbsapp.billingcustomers'),
        ),
    ]
