# Generated by Django 6.0.3 on 2026-04-20 12:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gbsapp', '0008_alter_billingcase_billing_cust_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='billing_cust_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='gbsapp.billingcustomers'),
        ),
    ]
